# 사용자 정의 속성
profile:
  value : 'local'
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: final_test
    password: final_test
    driver-class-name: oracle.jdbc.OracleDriver
